<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType Condition="'$(TargetFramework)' != 'net10.0'">Exe</OutputType>
		<RootNamespace>LittleLearner</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>LittleLearner</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.littlelearner</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\dev\vs\editor\editor.main.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\actionbar\actionbar.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\aria\aria.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\button\button.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\codicons\codicon\codicon-modifiers.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\codicons\codicon\codicon.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\contextview\contextview.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\countBadge\countBadge.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\dnd\dnd.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\dropdown\dropdown.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\findinput\findInput.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\hover\hoverWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\iconLabel\iconlabel.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\inputbox\inputBox.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\keybindingLabel\keybindingLabel.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\list\list.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\mouseCursor\mouseCursor.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\progressbar\progressbar.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\sash\sash.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\scrollbar\media\scrollbars.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\selectBox\selectBox.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\selectBox\selectBoxCustom.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\severityIcon\media\severityIcon.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\splitview\splitview.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\table\table.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\toggle\toggle.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\toolbar\toolbar.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\base\browser\ui\tree\media\tree.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\controller\editContext\native\nativeEditContext.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\controller\editContext\textArea\textAreaEditContext.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\gpu\css\media\decorationCssRuleExtractor.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\blockDecorations\blockDecorations.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\currentLineHighlight\currentLineHighlight.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\decorations\decorations.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\glyphMargin\glyphMargin.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\gpuMark\gpuMark.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\indentGuides\indentGuides.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\lineNumbers\lineNumbers.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\linesDecorations\linesDecorations.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\marginDecorations\marginDecorations.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\margin\margin.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\minimap\minimap.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\overlayWidgets\overlayWidgets.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\rulers\rulers.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\scrollDecoration\scrollDecoration.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\selections\selections.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\viewCursors\viewCursors.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\viewLines\viewLines.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\viewParts\whitespace\whitespace.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\widget\codeEditor\editor.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\widget\diffEditor\components\accessibleDiffViewer.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\widget\diffEditor\style.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\widget\markdownRenderer\browser\renderedMarkdown.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\browser\widget\multiDiffEditor\style.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\anchorSelect\browser\anchorSelect.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\bracketMatching\browser\bracketMatching.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\codeAction\browser\lightBulbWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\codelens\browser\codelensWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\colorPicker\browser\colorPicker.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\dnd\browser\dnd.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\dropOrPasteInto\browser\postEditWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\find\browser\findOptionsWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\find\browser\findWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\floatingMenu\browser\floatingMenu.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\folding\browser\folding.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\gotoError\browser\media\gotoErrorWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\gotoSymbol\browser\link\goToDefinitionAtPosition.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\gotoSymbol\browser\peek\referencesWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\hover\browser\hover.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\inlineCompletions\browser\hintsWidget\inlineCompletionsHintsWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\inlineCompletions\browser\view\ghostText\ghostTextView.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\inlineCompletions\browser\view\inlineEdits\view.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\inlineProgress\browser\inlineProgressWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\inPlaceReplace\browser\inPlaceReplace.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\linkedEditing\browser\linkedEditing.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\links\browser\links.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\message\browser\messageController.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\middleScroll\browser\middleScroll.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\parameterHints\browser\parameterHints.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\peekView\browser\media\peekViewWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\placeholderText\browser\placeholderText.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\rename\browser\renameWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\snippet\browser\snippetSession.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\stickyScroll\browser\stickyScroll.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\suggest\browser\media\suggest.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\symbolIcons\browser\symbolIcons.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\unicodeHighlighter\browser\bannerController.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\unicodeHighlighter\browser\unicodeHighlighter.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\wordHighlighter\browser\highlightDecorations.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\contrib\zoneWidget\browser\zoneWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\standalone\browser\inspectTokens\inspectTokens.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\standalone\browser\iPadShowKeyboard\iPadShowKeyboard.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\standalone\browser\quickInput\standaloneQuickInput.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\editor\standalone\browser\standalone-tokens.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\platform\actions\browser\menuEntryActionViewItem.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\platform\actionWidget\browser\actionWidget.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\platform\hover\browser\hover.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\platform\opener\browser\link.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\esm\vs\platform\quickinput\browser\media\quickInput.css" />
	  <MauiCss Remove="Resources\Raw\wwwroot\monaco-editor\min\vs\editor\editor.main.css" />
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Include="CodeEditor.html">
	    <LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
	  </MauiAsset>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CfgComparer\ImportCFG\CfgCompLib.csproj" />
	  <ProjectReference Include="..\LimitCSolver\LimitCGenerator\LimitCGenerator.csproj" />
	  <ProjectReference Include="..\LimitCSolver\LimitCInterpreter\LimitCInterpreter.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="LCS\Modals\ColorMapping.xaml.cs">
	    <DependentUpon>ColorMapping.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="CFG\CfgComparer.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="LCS\LimitCSolver.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="LCS\Modals\CodeCreationConfiguratoin.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="LCS\Modals\ColorMapping.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>
</Project>
